spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

server:
  port: ${APPLICATION_PORT}

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true

jwt:
  secret-key: ${SECRET_KEY}
  accessTokenExp: ${ACCESSTOKEN_EXP}

oauth:
  kakao:
    client-id: ${CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
